name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: 'Version (e.g. "1.0.0-rc1")'

jobs:
  publish:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Install node
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install --prefer-offline --no-fund --no-progress

    - name: Initialize deployment
      id: deployment
      uses: actions/github-script@v3.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const tag = /^[0-9]+\.[0-9]+\.[0-9]+$/.test("${{ github.event.inputs.version }}") ? 'latest' : 'preview';
          const deployment = await github.repos.createDeployment({
            environment: tag,
            ref: '${{ github.sha }}',
            owner: context.repo.owner,
            repo: context.repo.repo
          });
          core.setOutput('id', deployment.data.id);
          core.setOutput('tag', tag);

    - name: Parameters
      run: |
        echo Branch ${{ github.ref }}
        echo Version ${{ github.event.inputs.version }}
        echo NPM Tag ${{ steps.deployment.outputs.tag }}
        echo Deployment ${{ steps.deployment.outputs.id }}

    - name: Build & Test
      run: |
        npm run build -- --version ${{ github.event.inputs.version }} --tag ${{ steps.deployment.outputs.tag }}
        npm run test:postbuild

    - name: Create Release
      id: release
      uses: actions/github-script@v3.1
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const release = await github.repos.createRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag_name: 'v${{ github.event.inputs.version }}',
            target_commitish: context.sha,
            name: '${{ github.event.inputs.version }}',
            body: '',
            draft: false,
            prerelease: '${{ steps.deployment.outputs.tag }}' !== 'latest'
          });
          core.setOutput('upload_url', release.data.upload_url);

    - name: Install VSCE
      run: npm install -g vsce

    - name: Create VSIX
      run: vsce package
      working-directory: package

    - name: Attach VSIX
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./package/wildpeaks-theme-${{ github.event.inputs.version }}.vsix
        asset_name: theme.vsix
        asset_content_type: application/gzip

    - name: Publish to Marketplace
      if: steps.deployment.outputs.tag == 'latest'
      run: vsce publish -p ${{ secrets.MICROSOFT_DEPLOY_KEY }}
      working-directory: package

    - name: On success
      if: success()
      uses: actions/github-script@v3.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: '${{ steps.deployment.outputs.id }}',
            state: 'success'
          });

    - name: On error
      if: failure() || cancelled()
      uses: actions/github-script@v3.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: '${{ steps.deployment.outputs.id }}',
            state: 'failure'
          });
