name: Test
on:
  push:
    branches:
    - main
    - features/**
    - dependabot/**
  pull_request:
    branches:
    - main
jobs:
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: 14.x
      - run: npm install --prefer-offline --no-fund --no-progress
      - run: npm run lint
      - run: npm run build
      - run: npm run test:postbuild
