name: Tests
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
jobs:
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Download sources
        uses: actions/checkout@v2.3.4

      - name: Use Node LTS
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Lint sources
        run: npm run lint

      - name: Build the themes
        run: npm run build

      - name: Run tests
        run: npm test
